version: 1
builder:
  configs:
    - documentation_targets:
      - Stores
      - Blueprints
      - UserDefaultsStore
      - FileSystemStore
      - CoreDataStore
      - KeychainStore
      - TestUtils
